name = "nokanban"
main = "src/index.ts"
account_id = "9c76768311f305cecf8b02a25969e3c3"
compatibility_date = "2025-12-10"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "nokanban-db"
database_id = "8d74fd64-ec6d-41d3-89ea-e5fecc9c7021"
migrations_dir = "drizzle"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "nokanban-bucket"
preview_bucket_name = "nokanban-bucket-preview"

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "a7854e39656047e0be2873bd4c93cd05"
preview_id = "6a95df84f0e04abaa491637b62bb5b49"

[triggers]
crons = ["0 0 * * *"]
